// Extracted full data from original.js
const categoryColors = {
      home:         "#E8501A",   // corallo scurito (brand)
      beach:        "#0EA5E9",   // azzurro cielo atlantico
      nightlife:    "#7C3AED",   // viola profondo
      culture:      "#B45309",   // ambra/ocra antico
      gastro:       "#9D1348",   // borgogna sherry
      transport:    "#1D4ED8",   // blu royal segnaletica
      nature:       "#16A34A",   // verde foresta botanico
      nautica:      "#0C4A6E",   // blu navy club nautico
      supermercado: "#0D9488",   // teal acqua retail
    };

// alias for categoryColors if needed
const catColors = categoryColors;

const places = [
      { id:"home",       lat:36.588769, lng:-6.231999, title:"OlasDelSur",          category:"home",      icon:"🏠", address:"Avenida de la Bajamar 88",                  desc:"Tu refugio estival en el Guadalete. Acceso peatonal a la playa. Ribera del Marisco a 20 min a pie.", desc_en:"Your summer retreat on the Guadalete. Walking access to the beach. Ribera del Marisco 20 min walk.", desc_it: "Il tuo rifugio estivo sul Guadalete. Accesso a piedi alla spiaggia. Ribera del Marisco a 20 min a piedi.", rating:null,    link:null },
      { id:"puntilla",   lat:36.584956, lng:-6.23841, title:"Playa de la Puntilla",                 category:"beach",     icon:"🏖️",address:"Playa de la Puntilla, El Puerto de Santa María",desc:"A solo 600m. 2,5 km de playa dorada con bares e chiringuitos, apta para perros. La más cercana al casco histórico. Pinar de las Dunas de San Antón.", desc_en:"Just 600m away. 2.5 km of golden beach with bars and chiringuitos, dog-friendly. Closest to the historic centre.", desc_it: "A soli 600m. 2,5 km di spiaggia dorata con bar e chiringuitos, adatta ai cani. La più vicina al centro storico.", rating:"4.2★",  link:"https://maps.google.com/?q=Playa+de+la+Puntilla+El+Puerto+de+Santa+Maria" },
      { id:"valdelagrana",lat:36.5737, lng:-6.2253, title:"Playa de Valdelagrana",                category:"beach",     icon:"🏖️",address:"Valdelagrana, El Puerto de Santa María",       desc:"La playa más famosa. 2+ km, paseo marítimo con bares y restaurantes, surf y kitesurf.", desc_en:"The most famous beach. 2+ km, seafront promenade with bars and restaurants, surf and kitesurf.", desc_it: "La spiaggia più famosa. 2+ km, lungomare con bar e ristoranti, surf e kitesurf.", rating:"4.2★",  link:"https://maps.google.com/?q=Playa+de+Valdelagrana+El+Puerto+de+Santa+Maria" },
      { id:"muralla",    lat:36.580832, lng:-6.262349, title:"Playa La Muralla (Puerto Sherry)",     category:"beach",     icon:"🏖️",address:"Puerto Sherry, El Puerto de Santa María",       desc:"Playa Bandera Azul resguardada del viento. Vistas panorámicas a la bahía de Cádiz.", desc_en:"Blue Flag beach sheltered from the wind. Panoramic views over the Bay of Cádiz.", desc_it: "Spiaggia Bandiera Blu riparata dal vento. Viste panoramiche sulla baia di Cadice.", rating:"4.5★",  link:"https://maps.google.com/?q=Playa+La+Muralla+Puerto+Sherry" },
      { id:"phiphi",     lat:36.582551, lng:-6.250359, title:"PhiPhi Beach",                         category:"nightlife", icon:"🍹", address:"Avenida del Puerto, Puerto Sherry, 11500",     desc:"Bar al aire libre con impresionantes vistas al atardecer de Cádiz. Cócteles tropicales, música lounge. Horario: todos los días 15:30–00:00.", desc_en:"Open-air bar facing the bay with stunning Cádiz sunset views. Tropical cocktails, lounge music. Hours: daily 3:30 PM–midnight.", desc_it: "Bar all'aperto con viste spettacolari sul tramonto di Cadice. Cocktail tropicali, musica lounge. Orario: tutti i giorni 15:30–00:00.", rating:"★★★",   link:"https://www.instagram.com/phiphibeachpuertosherry/" },
      { id:"margarita",  lat:36.582276, lng:-6.250725, title:"Margarita Puerto Sherry",              category:"nightlife", icon:"🌅", address:"Puerto Sherry, El Puerto de Santa María",       desc:"A place for happiness — Music, sun & drinks. Bar de cócteles con terraza vista marina. Abierto todos los días. Reservas: 601 88 50 51.", desc_en:"A place for happiness — Music, sun & drinks. Cocktail bar with sea-view terrace. Open every day. Bookings: 601 88 50 51.", desc_it: "Un luogo di felicità — Musica, sole e drink. Cocktail bar con terrazza vista mare. Aperto ogni giorno.", rating:"★★★★",  link:"https://www.instagram.com/margaritapuertosherry/" },
      { id:"canalla",    lat:36.581865, lng:-6.250394, title:"Playa Canalla",                        category:"nightlife", icon:"🎶", address:"Puerto Sherry, El Puerto de Santa María",       desc:"Beach club boho-chic a orillas del mar. Espíritu Formentera — colores crema, madera y cálidos. Jueves, viernes y sábado. 21K seguidores Instagram.", desc_en:"Boho-chic beach club at the water's edge. Formentera spirit — cream, wood and warm tones. Thu, Fri & Sat. 21K Instagram followers.", desc_it: "Beach club boho-chic in riva al mare. Spirito Formentera — colori crema, legno e caldi. Gio, Ven e Sab.", rating:"★★★★★", link:"https://playacanalla.com" },
      { id:"lioclub",   lat:36.5868786, lng:-6.2337538, title:"Lio Club Puntilla Playa",              category:"nightlife", icon:"🎭", address:"Av. de la Bajamar, El Puerto de Santa María",  desc:"Club de ocio nocturno frente al mar, junto a la Playa de la Puntilla. Ambiente festivo con terraza costera. Reservas: +34 662 33 70 28. Temporalmente cerrado.", desc_en:"Seafront nightclub next to Playa de la Puntilla. Festive atmosphere with a coastal terrace. Bookings: +34 662 33 70 28. Currently temporarily closed.", desc_it: "Nightclub fronte mare vicino a Playa de la Puntilla. Atmosfera festosa con terrazza costiera. Temporaneamente chiuso.", rating:"★★★★½", link:"https://maps.app.goo.gl/GiSgZ18XSrp8zCn27" },
      { id:"cristalera", lat:36.597649, lng:-6.2236862, title:"Bar La Cristalera",                    category:"nightlife", icon:"🎹", address:"Pl. de las Galeras Reales s/n, El Puerto de Santa María", desc:"Bar musical y piano bar junto al río Guadalete, en pleno centro. Copas, DJ y música en vivo. Abre desde las 15:30. Tel: +34 647 84 54 47.", desc_en:"Music bar and piano bar by the Guadalete river in the city centre. Drinks, DJ and live music. Opens from 3:30 PM. Tel: +34 647 84 54 47.", desc_it: "Music bar e piano bar vicino al fiume Guadalete in centro. Drink, DJ e musica dal vivo. Apre dalle 15:30.", rating:"★★★★", link:"https://m.facebook.com/lacristaleracopas" },
      { id:"banana",    lat:36.5982164, lng:-6.2242166, title:"Banana Club",                          category:"nightlife", icon:"🍌", address:"C. Ribera del Marisco 13, El Puerto de Santa María", desc:"La discoteca más animada del Puerto, referencia de la vida nocturna desde hace 5 años. Abre a las 23:00. Reservas WhatsApp: 697 85 00 50.", desc_en:"The liveliest club in El Puerto, a nightlife landmark for 5 years. Opens at 11 PM. Bookings WhatsApp: 697 85 00 50.", desc_it: "Il club più vivace di El Puerto, un punto di riferimento da 5 anni. Apre alle 23:00. Prenotazioni WhatsApp: 697 85 00 50.", rating:"★★★", link:"https://bananaelpuerto.com" },
      { id:"castillo",   lat:36.596356, lng:-6.226796, title:"Castillo de San Marcos",               category:"culture",   icon:"🏰", address:"Plaza del Castillo s/n, El Puerto de Santa María",desc:"Fortaleza del s. XII construida sobre las ruinas de una mezquita árabe. Vinculada a los viajes de Colón. Incluye degustaciones de jerez.", desc_en:"12th-century fortress built on the ruins of an Arab mosque. Linked to Columbus's voyages. Includes sherry tastings.", desc_it: "Fortezza del XII secolo costruita sulle rovine di una moschea araba. Legata ai viaggi di Colombo. Include degustazioni di sherry.", rating:"★★★★",  link:"https://maps.google.com/?q=Castillo+San+Marcos+El+Puerto+de+Santa+Maria" },
      { id:"plazatoros",  lat:36.5967774, lng:-6.2327389, title:"Real Plaza de Toros",                 category:"culture",   icon:"🐂", address:"Pl. de Elías Ahuja s/n, El Puerto de Santa María",    desc:"Plaza de toros construida en 1880. Icono arquitectónico de El Puerto. Aforo de 15.000 localidades. Visitas guíadas disponibles.",                desc_en:"Bullring built in 1880. Architectural icon of El Puerto. Capacity 15,000. Guided tours available.", desc_it: "Plaza de toros costruita nel 1880. Icona architettonica di El Puerto. Visite guidate disponibili.", rating:"4.3★", link:"https://www.elpuertodesantamaria.es/plaza-de-toros/" },
      { id:"alberti",     lat:36.5981903, lng:-6.2282341, title:"Museo Fundación Rafael Alberti",        category:"culture",   icon:"🎨", address:"C. Santo Domingo 25, El Puerto de Santa María",         desc:"Museo dedicado al poeta Rafael Alberti, Premio Cervantes 1983. Exposiciones permanentes y temporales. Audio guías en varios idiomas. Entrada: 4,50€.", desc_en:"Museum dedicated to poet Rafael Alberti, 1983 Cervantes Prize winner. Permanent and temporary exhibitions. Audio guides available. Entry: €4.50.", desc_it: "Museo dedicato al poeta Rafael Alberti, premio Cervantes 1983. Mostre permanenti e temporanee. Audioguide disponibili.", rating:"4.6★ (489)", link:"http://www.rafaelalberti.com/" },
      { id:"valdivieso",  lat:36.595989,  lng:-6.226993,  title:"Palacio de Valdivieso",                category:"culture",   icon:"🏛️", address:"C. de la Palma 4, El Puerto de Santa María",             desc:"Palacio barroco del siglo XVIII en el centro histórico. Ejemplo destacado de la arquitectura palaciega de El Puerto.",                             desc_en:"18th-century Baroque palace in the historic centre. A fine example of palatial architecture in El Puerto.", desc_it: "Palazzo barocco del XVIII secolo nel centro storico. Un eccellente esempio di architettura palaziale di El Puerto.", rating:"4.5★", link:"https://maps.google.com/?q=Palacio+de+Valdivieso+El+Puerto+de+Santa+Maria" },
      { id:"aranibar",    lat:36.5965023, lng:-6.2261947, title:"Palacio de Araníbar",                  category:"culture",   icon:"🏩", address:"Pl. Alfonso X el Sabio 9, El Puerto de Santa María",     desc:"Palacio histórico que alberga la Oficina de Turismo de El Puerto. Visita gratuita con patio interior. Centro de interpretación de la ciudad.",       desc_en:"Historic palace housing El Puerto's Tourist Office. Free entry with historic courtyard. City interpretation centre.", desc_it: "Storico palazzo che ospita l'Ufficio del Turismo. Ingresso gratuito con cortile storico. Centro di interpretazione della città.", rating:"4.3★ (75)", link:"http://www.elpuertodesantamaria.es/" },
      { id:"iglesia",     lat:36.5996956, lng:-6.2288963, title:"Iglesia Mayor Prioral",                category:"culture",   icon:"⛪", address:"Pl. de España s/n, El Puerto de Santa María",            desc:"Iglesia gótico-renacentista del s. XV. Principal templo católico de El Puerto, en la Plaza de España. 2.087 reseñas en Google.",                         desc_en:"15th-century Gothic-Renaissance church. Main Catholic temple of El Puerto on Plaza de España. 2,087 Google reviews.", desc_it: "Chiesa gotico-rinascimentale del XV secolo. Principale tempio cattolico di El Puerto in Plaza de España.", rating:"4.5★ (2.087)", link:"https://iglesiamayorprioralelpuerto.com" },
      { id:"osborne",    lat:36.595001, lng:-6.229006, title:"Bodegas Osborne",                      category:"gastro",   icon:"🍷", address:"Calle Los Moros 7, El Puerto de Santa María",   desc:"La más visitada: 33.603 visitas/año. Casa del Toro de Osborne. Degustaciones de jerez y brandy. Imprescindible.", desc_en:"Most visited: 33,603 visits/year. Home of the Osborne Bull. Sherry and brandy tastings. Absolute must.", desc_it: "La più visitata: 33.603 visite all'anno. Casa del Toro Osborne. Degustazioni di sherry e brandy. Imperdibile.", rating:"★★★★★", link:"https://maps.google.com/?q=Bodegas+Osborne+El+Puerto+de+Santa+Maria" },
      { id:"aponiente",  lat:36.6031417, lng:-6.2164111, title:"Aponiente", category:"gastro", icon:"⭐", address:"C. Francisco Cossi Ochoa s/n, El Puerto de Santa María", desc:"Restaurante 3 Estrellas Michelin del chef Ángel León. Alta cocina del mar en un antiguo molino de mareas. Menús degustación con maridaje.", desc_en:"3 Michelin Star restaurant by chef Ángel León. Avant-garde sea cuisine in a historic tidal mill. Tasting menus with wine pairing.", desc_it: "Ristorante 3 stelle Michelin dello chef Ángel León. Alta cucina di mare in un antico mulino a marea storico.", rating:"4.7★", link:"https://aponiente.com" },
      { id:"ribera",     lat:36.5991, lng:-6.2235, title:"Ribera del Marisco",                   category:"gastro",    icon:"🦞", address:"Ribera del Marisco, El Puerto de Santa María",   desc:"El paseo del marisco. Concentración de bares y restaurantes junto al río Guadalete. Muy animado por las noches.", desc_en:"The seafood promenade. Bars and restaurants along the Guadalete River. Buzzing every evening.", desc_it: "Il lungomare del pesce. Bar e ristoranti lungo il fiume Guadalete. Molto vivace ogni sera.", rating:"★★★★★", link:"https://maps.google.com/?q=Ribera+del+Marisco+El+Puerto+de+Santa+Maria" },
      { id:"venencia",   lat:36.5893859, lng:-6.2312539, title:"Restaurante La Venencia",           category:"gastro",    icon:"🐟", address:"Av. de la Bajamar 78-80, El Puerto de Santa María", desc:"Restaurante frente al mar en la Avenida de la Bajamar. Cocina tradicional andaluza y mariscos frescos con vistas a la marina.", desc_en:"Seafront restaurant on Avenida de la Bajamar. Traditional Andalusian cuisine and fresh seafood with marina views.", desc_it: "Ristorante fronte mare in Avenida de la Bajamar. Cucina tradizionale andalusa e pesce fresco con vista sulla marina.", rating:"4.0★", link:"https://maps.google.com/?q=Restaurante+La+Venencia+El+Puerto+de+Santa+Maria" },
      { id:"barpepito",  lat:36.5917628, lng:-6.2342126, title:"Bar Pepito",                         category:"gastro",    icon:"🥘", address:"C. Crucero Baleares 7, El Puerto de Santa María",   desc:"Bar de tapas muy popular. Coquinas y solomillo al queso de oveja. Excelente relación calidad-precio. 1.258 reseñas Google.", desc_en:"Very popular tapas bar. Coquinas clams and beef fillet with sheep cheese. Excellent value for money. 1,258 Google reviews.", desc_it: "Tapas bar molto popolare. Telline e filetto di manzo al formaggio di pecora. Ottimo rapporto qualità-prezzo.", rating:"4.3★", link:"https://www.facebook.com/Bar-Pepito-282424711778851" },
      { id:"torotapas",  lat:36.5949591, lng:-6.2291652, title:"Toro Tapas (Osborne)",               category:"gastro",    icon:"🐂", address:"C. Los Moros 7, El Puerto de Santa María",          desc:"Restaurante de tapas dentro de Bodegas Osborne. Cocina española en el corazón de la bodega más icónica de El Puerto. 2.713 reseñas.", desc_en:"Tapas restaurant inside Bodegas Osborne. Spanish cuisine in the heart of El Puerto's most iconic winery. 2,713 reviews.", desc_it: "Ristorante di tapas all'interno di Bodegas Osborne. Cucina spagnola nel cuore della cantina più iconica.", rating:"4.4★", link:"https://www.osborne.es/es/restaurante-osborne-toro-tapas-el-puerto-de-santa-maria" },
      { id:"ditaly",     lat:36.5977907, lng:-6.2246438, title:"DITALY",                              category:"gastro",    icon:"🍕", address:"C. Luna 1, El Puerto de Santa María",               desc:"Restaurante italiano con 4,8★ en Google. Pizzas artesanas, pasta fresca y tiramisú de pistacho. Cocina italiana para compartir.", desc_en:"Italian restaurant with 4.8★ on Google. Artisan pizzas, fresh pasta and pistachio tiramisu. Italian cuisine for sharing.", desc_it: "Ristorante italiano con 4,8★. Pizze artigianali, pasta fresca e tiramisù al pistacchio. Cucina italiana da condividere.", rating:"4.8★", link:"https://www.ditaly.es/locales/local-puerto-de-santa-maria/" },
      { id:"tabernachef",lat:36.5999432, lng:-6.2230816, title:"La Taberna del Chef del Mar",         category:"gastro",    icon:"🎣", address:"C. Puerto Escondido 6, El Puerto de Santa María",    desc:"Taberna del universo culinario de Ángel León. Tapas y mariscos elevados en un ambiente informal y animado.", desc_en:"Tavern from Ángel León's culinary universe. Elevated tapas and seafood in a lively, informal setting.", desc_it: "Taverna dell'universo culinario di Ángel León. Tapas e pesce elevati in un ambiente vivace e informale.", rating:"4.4★", link:"http://latabernadelchefdelmar.com/" },
      { id:"romerijo",   lat:36.5986168, lng:-6.2238748, title:"Romerijo",                            category:"gastro",    icon:"🦐", address:"C. Ribera del Marisco 1, El Puerto de Santa María",  desc:"Marisquería icónica de El Puerto. 13.100 reseñas Google. Tortillitas de camarones, gambas y erizos. Temporalmente cerrado (incendio ene. 2026).", desc_en:"Iconic seafood institution in El Puerto. 13,100 Google reviews. Shrimp tortillas, prawns and sea urchins. Temporarily closed (fire Jan 2026).", desc_it: "Iconica istituzione del pesce a El Puerto. Tortillitas de camarones, gamberi e ricci di mare. Temporaneamente chiusa.", rating:"4.0★", link:"https://romerijo.com" },
      { id:"colosia",     lat:36.5923196, lng:-6.2286547, title:"Bodegas Gutiérrez Colosía",       category:"gastro",    icon:"🍷", address:"Av. de la Bajamar 40, El Puerto de Santa María",   desc:"Bodega histórica a orillas del río Guadalete. Vinos de Jerez excelentes.", desc_en:"Historic winery on the banks of the Guadalete river. Excellent sherry wines.", desc_it: "Cantina storica sulle rive del fiume Guadalete. Ottimi vini sherry.", rating:"4.6★", link:"https://maps.app.goo.gl/bbaPpTEj6affw9dA6" },
      { id:"nuevadorada", lat:36.5933721, lng:-6.2276785, title:"La Nueva Dorada",                 category:"gastro",    icon:"🐟", address:"C. Ribera del Marisco, El Puerto de Santa María",  desc:"Clásico restaurante de mariscos en la Ribera del Marisco. Pescado fresco y frito.", desc_en:"Classic seafood restaurant on Ribera del Marisco. Fresh and fried fish.", desc_it: "Classico ristorante di pesce sulla Ribera del Marisco. Pesce fresco e fritto.", rating:"4.2★", link:"https://maps.app.goo.gl/n1Pwn5XpyEVKUkvK9" },
      { id:"newgoldbar",  lat:36.5942542, lng:-6.2267958, title:"New Gold Bar",                    category:"gastro",    icon:"🍻", address:"El Puerto de Santa María",                         desc:"Bar muy animado para tomar unas cervezas y tapas con buen ambiente.", desc_en:"Very lively bar for beers and tapas with a great atmosphere.", desc_it: "Bar molto vivace per birre e tapas con un'ottima atmosfera.", rating:"4.4★", link:"https://maps.app.goo.gl/WufQrwsD8HyMm4uq7" },
      { id:"tren", lat:36.6040121, lng:-6.2179023, title:"Estación de Tren", category:"transport", icon:"🚆", address:"Pl. de la Estación s/n, El Puerto de Santa María", desc:"Cercanías C1 (Cádiz–Jerez–Sevilla), Alvia y Media Distancia. Conexión directa con Sevilla ~1h y Cádiz ~30 min.", desc_en:"Cercanías C1 (Cádiz–Jerez–Seville), Alvia and MD services. Direct connection to Seville ~1h and Cádiz ~30 min.", desc_it: "Cercanías C1 (Cadice–Jerez–Siviglia), Alvia e Media Distancia. Collegamento diretto con Siviglia ~1h e Cadice ~30 min.", rating:"3.0★", link:"http://www.adif.es/es_ES/infraestructuras/estaciones/51400/informacion_000311.shtml" },
      { id:"catamaran",  lat:36.593651, lng:-6.226607, title:"Catamaran → Cádiz",                   category:"transport", icon:"⛵", address:"Estación Marítima, El Puerto de Santa María",   desc:"15+ travesías al día. Solo 25–30 minutos para llegar a Cádiz. La forma más bonita de visitar la ciudad.", desc_en:"15+ crossings daily. Just 25–30 minutes to Cádiz. The most beautiful way to visit the city.", desc_it: "Oltre 15 corse al giorno. Solo 25–30 minuti per Cadice. Il modo più bello per visitare la città.", rating:null,    link:"https://maps.google.com/?q=Estacion+Maritima+El+Puerto+de+Santa+Maria" },
      { id:"torunos",    lat:36.572096, lng:-6.2162876, title:"Parque Natural Los Toruños",          category:"nature",    icon:"🌿", address:"Av. del Mar 7, El Puerto de Santa María",          desc:"Reserva natural de marismas con paseos de madera, alquiler de kayaks y bicicletas, observación de aves y zonas de picnic. Abierto 24h. Tel: +34 856 58 05 24.", desc_en:"Tidal marsh nature reserve with boardwalks, kayak & bike rental, birdwatching and picnic areas. Open 24h. Tel: +34 856 58 05 24.", desc_it: "Riserva naturale con passerelle, noleggio kayak e bici, birdwatching e aree picnic. Aperto 24 ore.", rating:"4.7★",  link:"https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-naturales-protegidos" },
      { id:"calita", lat:36.583343, lng:-6.268132, title:"Playa la Calita", category:"beach", icon:"🏖️", address:"Puerto Sherry, El Puerto de Santa María", desc:"Cala pequeña y recogida junto a Puerto Sherry. Aguas tranquilas, fondo arenoso, perfecta para familias. Acceso a pie desde el paseo.", desc_en:"Small sheltered cove by Puerto Sherry. Calm waters, sandy bottom, perfect for families. Walking access from the promenade.", desc_it: "Piccola cala riparata vicino a Puerto Sherry. Acque calmi, fondo sabbioso, perfetta per le famiglie.", rating:"★★★★", link:"https://maps.google.com/?q=Playa+la+Calita+Puerto+Sherry+El+Puerto+de+Santa+Maria" },
      { id:"rcn", lat:36.5895, lng:-6.2309, title:"Real Club Náutico", category:"nautica", icon:"⚓", address:"Avenida de la Bajamar 13, El Puerto de Santa María", desc:"Club náutico histórico a orillas del Guadalete. Restaurante-bar <b>La Venecia</b> (tapas, arroces · 9:00–00:00). Club de copas <b>Chang Bay</b> (15:00–02:00). Pantalán con alquiler de motos de agua y embarcaciones con/sin patrón. Pistas de pádel y tenis.", desc_en:"Historic yacht club on the Guadalete. Restaurant <b>La Venecia</b> (tapas & rice · 9am–midnight). <b>Chang Bay</b> club (3pm–2am). Pontoon with jet ski & boat rental (skippered or bareboat). Padel & tennis courts.", desc_it: "Storico yacht club sul Guadalete. Ristorante La Venecia. Club Chang Bay. Noleggio moto d'acqua e barche. Sport.", rating:"★★★★", link:"https://www.rcnpsm.es" },
      { id:"puertosherry",lat:36.5803, lng:-6.2552, title:"Puerto Sherry Marina",                 category:"nautica",    icon:"⚓", address:"Puerto Sherry, El Puerto de Santa María",       desc:"Marina moderna con vela, clubes náuticos y restaurantes. Atardeceres espectaculares sobre la bahía de Cádiz.", desc_en:"Modern marina with sailing, yacht clubs and restaurants. Spectacular sunsets over the Bay of Cádiz.", desc_it: "Marina moderna con vela, yacht club e ristoranti. Tramonti spettacolari sulla baia di Cadice.", rating:"★★★★★", link:null },
      { id:"mercadona",  lat:36.591933, lng:-6.230806, title:"S. El Jamón (6 min)", category:"supermercado", icon:"🛒", address:"Av. de la Bajamar", desc:"El supermercado più cercano al Airbnb. Cadena andaluza con prodotti freschi.", desc_en:"The closest supermarket to the Airbnb. Andalusian chain with fresh produce.", desc_it: "Il supermercato più vicino all'Airbnb. El Jamón è una catena andalusa con prodotti freschi.", rating:"4.1★", link:"https://maps.app.goo.gl/kYb8NvJs5nnVXmXT9" },
      { id:"aldi",       lat:36.593597,  lng:-6.228834, title:"Aldi",             category:"supermercado", icon:"🛒", address:"C. Valdés s/n", desc:"Supermercado Aldi. Precios bajos garantizzati e prodotti locali.", desc_en:"Aldi supermarket. Guaranteed low prices and local produce section.", desc_it: "Supermercato Aldi. Prezzi bassi garantiti, prodotti locali e articoli stagionali.", rating:"4.2★", link:"https://maps.app.goo.gl/eLoWrx2oRU8eyNKa9" },
      { id:"mercadona2",lat:36.591351,  lng:-6.237841, title:"Mercadona Dunas",  category:"supermercado", icon:"🛒", address:"Rda. de las Dunas 7", desc:"Secondo Mercadona de El Puerto. Gran superficie e parking gratuito.", desc_en:"Second Mercadona in El Puerto. Large store with free parking.", desc_it: "Secondo Mercadona di El Puerto, zona Dunas. Grande negozio, parcheggio gratuito e ampia sezione freschi.", rating:"4.1★", link:"https://maps.app.goo.gl/iMzrKyCVCL2jZtUU6" },
      { id:"dia",        lat:36.594634,  lng:-6.237477, title:"S. Dia", category:"supermercado", icon:"🛒", address:"Av. Pintor Antonio Sevilla", desc:"Supermercados Dia, cadena española. Excelente relación qualità-prezzo.", desc_en:"Dia supermarket, Spanish chain with great value for money.", desc_it: "Supermercato Dia, catena spagnola con ottimo valore. Prodotti a marchio proprio e offerte giornaliere.", rating:"3.9★", link:"https://maps.app.goo.gl/ZtKo7JEHFALN6Zho9" },
    ];

const poiData = [
    {
      id: 'home', cat: 'home', emoji: '🏠',
      name: 'OlasDelSur',
      badge_es: 'Tu Airbnb', badge_en: 'Your Airbnb', badge_fr: 'Votre Airbnb', badge_de: 'Ihr Airbnb', badge_it: 'Il tuo Airbnb',
      desc_es: 'Tu base en El Puerto de Santa María. Apartamento recién renovado con 2 habitaciones para 4 personas, a 100m del río Guadalete y a 20 min a pie de la Ribera del Marisco.',
      desc_en: 'Your base in El Puerto de Santa María. Newly renovated 2-bedroom apartment for 4 guests, 100m from the Guadalete river and 20 min walk from the seafood promenade.',
      desc_fr: 'Votre base à El Puerto de Santa María. Appartement rénové avec 2 chambres pour 4 personnes, à 100m du fleuve Guadalete.',
      desc_de: 'Ihre Basis in El Puerto de Santa María. Frisch renoviertes 2-Zimmer-Apartment für 4 Gäste, 100m vom Guadalete-Fluss entfernt.',
      desc_it: 'La tua base a El Puerto de Santa María. Appartamento appena rinnovato con 2 camere per 4 persone, a 100m dal fiume Guadalete e a 20 min a piedi dalla Ribera del Marisco.',
      address: 'Avenida de la Bajamar 88, El Puerto de Santa María',
      hours_es: 'Check-in: 15:00 · Check-out: 11:00',
      hours_en: 'Check-in: 3:00 PM · Check-out: 11:00 AM',
      hours_it: 'Check-in: 15:00 · Check-out: 11:00',
      phone: null,
      rating: '4.9★ (42 reseñas)',
      link: 'https://www.airbnb.com/rooms/833027419091697738',
      maps: 'https://maps.google.com/?q=Avenida+Bajamar+88+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'puntilla', cat: 'beach', emoji: '🏖️',
      name: 'Playa de la Puntilla',
      name_fr: 'Plage de la Puntilla',
      name_it: 'Spiaggia della Puntilla',
      badge_es: 'A 600m · apta para perros', badge_en: '600m · dog-friendly', badge_fr: '600m · chiens bienvenus', badge_de: '600m · hundefreundlich', badge_it: '600m · adatta ai cani',
      desc_es: 'A solo 600m. Amplia playa de arena dorada de 2,5 km con bares y chiringuitos, apta para perros. La más cercana al casco histórico, con paseo marítimo y pinar.',
      desc_en: 'Only 600m away. 2.5 km of golden sand with bars and chiringuitos, dog-friendly. Closest to the historic centre, with promenade and pine forest.',
      desc_fr: 'À seulement 600m. Plage de 2,5 km avec bars et chiringuitos, accès chiens autorisé. La più proche du centre historique.',
      desc_de: 'Nur 600m entfernt. 2,5 km goldener Sand mit Bars und Chiringuitos, hundefreundlich. Am nächsten zur Altstadt.',
      desc_it: 'A soli 600m. Ampia spiaggia di sabbia dorata di 2,5 km con bar e chiringuitos, adatta ai cani. La più vicina al centro storico, con lungomare e pineta.',
      address: 'P.º Marítimo de la Puntilla, El Puerto de Santa María',
      hours_es: 'Abierta 24h',
      hours_en: 'Open 24h',
      hours_it: 'Aperta 24h',
      phone: null,
      rating: '4.3★ (2.084 reseñas)',
      link: 'https://maps.google.com/?q=Playa+de+la+Puntilla+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Playa+de+la+Puntilla+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'valdelagrana', cat: 'beach', emoji: '🏖️',
      name: 'Playa Valdelagrana',
      name_fr: 'Plage Valdelagrana',
      name_it: 'Spiaggia Valdelagrana',
      badge_es: 'Playa principal', badge_en: 'Main beach', badge_fr: 'Plage principale', badge_de: 'Hauptstrand', badge_it: 'Spiaggia principale',
      desc_es: 'La playa principal de El Puerto, extensa y bien equipada. Arena fina, aguas limpias, servicio de socorristas y amplia zona de chiringuitos. Ideal para familias.',
      desc_en: 'The main beach of El Puerto, extensive and well-equipped. Fine sand, clear water, lifeguards and plenty of beach bars. Ideal for families.',
      desc_fr: "La plage principale d'El Puerto, vaste et bien équipée. Sable fin, eaux claires, maîtres-nageurs et nombreux bars de plage.",
      desc_de: 'Der Hauptstrand von El Puerto, weitläufig und gut ausgestattet. Feiner Sand, klares Wasser, Rettungsschwimmer und viele Strandbars.',
      desc_it: 'La spiaggia principale di El Puerto, estesa e ben attrezzata. Sabbia fine, acque pulite, servizio di bagnini e ampia zona di chiringuitos. Ideale per le famiglie.',
      address: 'Playa de Valdelagrana, El Puerto de Santa María',
      hours_es: 'Abierta 24h',
      hours_en: 'Open 24h',
      hours_it: 'Aperta 24h',
      phone: null,
      rating: '4.4★',
      link: 'https://maps.google.com/?q=Playa+de+Valdelagrana+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Playa+de+Valdelagrana+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'muralla', cat: 'beach', emoji: '🏖️',
      name: 'Playa La Muralla',
      badge_es: 'Playa · Bandera Azul', badge_en: 'Beach · Blue Flag', badge_fr: 'Plage · Pavillon Bleu', badge_de: 'Strand · Blaue Flagge', badge_it: 'Spiaggia · Bandiera Blu',
      desc_es: 'Pequeña playa tranquila con arena dorada y vistas a las ruinas del castillo medieval. Situada junto a la marina de Puerto Sherry, con restaurantes cercanos y olas suaves.',
      desc_en: 'Small, peaceful beach with golden sand and views of medieval castle ruins. Located next to Puerto Sherry marina, with nearby restaurants and calm waves.',
      desc_fr: "Petite plage tranquille avec vue sur les ruines d'un château médiéval. Située près de la marina de Puerto Sherry.",
      desc_de: 'Kleiner, ruhiger Strand mit Blick auf mittelalterliche Burgruinen. Neben der Marina Puerto Sherry gelegen.',
      desc_it: 'Piccola spiaggia tranquilla con sabbia dorata e vista sulle rovine del castello medievale. Situata vicino alla marina di Puerto Sherry, con ristoranti nelle vicinanze e onde calmi.',
      address: 'P.º Sta. Catalina 3, El Puerto de Santa María',
      hours_es: 'Abierta 24h',
      hours_en: 'Open 24h',
      hours_it: 'Aperta 24h',
      phone: null,
      rating: '4.4★ (2.333 reseñas)',
      link: 'https://maps.google.com/?q=Playa+La+Muralla+Puerto+Sherry',
      maps: 'https://maps.google.com/?q=Playa+La+Muralla+Puerto+Sherry',
    },
    {
      id: 'calita', cat: 'beach', emoji: '🏖️',
      name: 'Playa la Calita',
      badge_es: 'Cala recogida', badge_en: 'Sheltered cove', badge_fr: 'Crique abritée', badge_de: 'Geschützte Bucht', badge_it: 'Cala riparata',
      desc_es: 'Cala pequeña y recogida junto a Puerto Sherry. Aguas tranquilas y fondo arenoso, perfecta para familias y para un baño tranquilo. Acceso a pie desde el paseo.',
      desc_en: 'Small sheltered cove by Puerto Sherry. Calm waters and sandy bottom, perfect for families and a peaceful swim. Walking access from the promenade.',
      desc_fr: "Petite crique abritée près de Puerto Sherry. Eaux calmes et fond sableux, idéale pour les familles.",
      desc_de: 'Kleine geschützte Bucht bei Puerto Sherry. Ruhige Gewässer und Sandboden, ideal für Familien.',
      desc_it: 'Piccola cala riparata vicino a Puerto Sherry. Acque tranquille e fondo sabbioso, perfetta per le famiglie e per un bagno rilassante. Accesso a piedi dal lungomare.',
      address: 'Puerto Sherry, El Puerto de Santa María',
      hours_es: 'Abierta 24h',
      hours_en: 'Open 24h',
      hours_it: 'Aperta 24h',
      phone: null,
      rating: '4.4★',
      link: 'https://maps.google.com/?q=Playa+la+Calita+Puerto+Sherry',
      maps: 'https://maps.google.com/?q=Playa+la+Calita+Puerto+Sherry',
    },
    {
      id: 'phiphi', cat: 'nightlife', emoji: '🍹',
      name: 'PhiPhi Beach',
      badge_es: 'Open Air Bar', badge_en: 'Open Air Bar', badge_fr: 'Bar en plein air', badge_de: 'Open-Air-Bar', badge_it: 'Bar all\'aperto',
      desc_es: 'Club de playa al aire libre en Puerto Sherry con vistas espectaculares a la bahía de Cádiz. DJ en directo, cócteles tropicales y atardecer atlántico. Uno de los bares más icónicos de la zona.',
      desc_en: 'Open-air beach club in Puerto Sherry with stunning views of the Bay of Cádiz. Live DJ sets, tropical cocktails and spectacular Atlantic sunsets. One of the most iconic bars in the area.',
      desc_fr: "Club de plage en plein air à Puerto Sherry avec une vue magnifique sur la baie de Cádiz. DJ en direct, cocktails tropicaux et couchers de soleil atlantiques.",
      desc_de: 'Open-Air-Strandclub in Puerto Sherry mit atemberaubender Aussicht auf die Bucht von Cádiz. Live-DJ-Sets, tropische Cocktails und spektakuläre Sonnenuntergänge.',
      desc_it: 'Beach club all\'aperto a Puerto Sherry con viste spettacolari sulla baia di Cadice. DJ set dal vivo, cocktail tropicali e tramonti atlantici. Uno dei bar più iconici della zona.',
      address: 'C. Puerto Serrano 9, Puerto Sherry, El Puerto de Santa María',
      hours_es: 'Lun–Dom: 17:30 – 00:00 (temporada)',
      hours_en: 'Mon–Sun: 5:30 PM – midnight (seasonal)',
      hours_it: 'Lun–Dom: 17:30 – 00:00 (stagionale)',
      phone: '+34 647 845 447',
      rating: '3.7★',
      link: 'https://www.instagram.com/phiphibeachpuertosherry/',
      maps: 'https://maps.google.com/?q=PhiPhi+Beach+Puerto+Sherry',
    },
    {
      id: 'margarita', cat: 'nightlife', emoji: '🌅',
      name: 'Margarita Puerto Sherry',
      badge_es: 'A Place for Happiness', badge_en: 'A Place for Happiness', badge_fr: 'Un lieu de bonheur', badge_de: 'Ein Ort des Glücks', badge_it: 'Un luogo di felicità',
      desc_es: 'Bar de cócteles con terraza y vistas al mar en Puerto Sherry. Ambiente relajado y festivo, música selecta y los mejores atardeceres de la bahía. Abierto todos los días.',
      desc_en: 'Cocktail bar with sea-view terrace at Puerto Sherry. Relaxed and joyful atmosphere, curated music and the best sunsets over the bay. Open every day.',
      desc_fr: 'Bar à cocktails avec terrasse vue mer à Puerto Sherry. Ambiance détendue et festive, musique sélectionnée et les plus beaux couchers de soleil.',
      desc_de: 'Cocktailbar mit Meerblick-Terrasse in Puerto Sherry. Entspannte und fröhliche Atmosphäre, ausgewählte Musik und die schönsten Sonnenuntergänge.',
      desc_it: 'Cocktail bar con terrazza vista mare a Puerto Sherry. Atmosfera rilassata e festosa, musica selezionata e i migliori tramonti della baia. Aperto tutti i giorni.',
      address: 'Puerto Sherry, El Puerto de Santa María',
      hours_es: 'Todos los días desde las 15:30',
      hours_en: 'Every day from 3:30 PM',
      hours_it: 'Tutti i giorni dalle 15:30',
      phone: '+34 601 885 051',
      rating: '★★★★',
      link: 'https://www.instagram.com/margaritapuertosherry/',
      maps: 'https://maps.google.com/?q=36.582276,-6.250725',
    },
    {
      id: 'canalla', cat: 'nightlife', emoji: '🎶',
      name: 'Playa Canalla',
      badge_es: 'Boho-Chic Beach Club', badge_en: 'Boho-Chic Beach Club', badge_fr: 'Beach Club Boho-Chic', badge_de: 'Boho-Chic Beach Club', badge_it: 'Beach Club Boho-Chic',
      desc_es: 'Beach club de estilo boho-chic a orillas del mar en Puerto Sherry. Espíritu Formentera, decoración en tonos crema y madera, elegancia y glamour. Parte del Grupo Banban.',
      desc_en: "Boho-chic beach club at the water's edge in Puerto Sherry. Formentera spirit, cream and wood décor, elegance and glamour. Part of Grupo Banban.",
      desc_fr: "Beach club boho-chic au bord de l'eau à Puerto Sherry. Esprit Formentera, décor crème et bois, élégance et glamour.",
      desc_de: 'Boho-Chic-Strandclub am Wasser in Puerto Sherry. Formentera-Atmosphäre, Creme-Holz-Dekor, Eleganz und Glamour.',
      desc_it: 'Beach club in stile boho-chic in riva al mare a Puerto Sherry. Spirito Formentera, decorazioni in toni crema e legno, eleganza e glamour. Parte del Gruppo Banban.',
      address: 'C. Puerto Serrano, Puerto Sherry, El Puerto de Santa María',
      hours_es: 'Jueves, Viernes y Sábado: 17:00 – tarde',
      hours_en: 'Thursday, Friday & Saturday: 5:00 PM – late',
      hours_it: 'Giovedì, Venerdì e Sabato: 17:00 – tardi',
      phone: '+34 620 691 271',
      rating: '4.2★',
      link: 'https://playacanalla.com',
      maps: 'https://maps.google.com/?q=Playa+Canalla+Puerto+Sherry',
    },
    {
      id: 'lioclub', cat: 'nightlife', emoji: '🎭',
      name: 'Lio Club Puntilla Playa',
      badge_es: 'Club nocturno frente al mar', badge_en: 'Seafront nightclub', badge_fr: 'Club nocturne en bord de mer', badge_de: 'Strandnaher Nachtclub', badge_it: 'Club notturno fronte mare',
      desc_es: 'Club nocturno situado en la Avenida de la Bajamar, a orillas del mar junto a la Playa de la Puntilla. Ambiente festivo con terraza costera. Actualmente temporalmente cerrado.',
      desc_en: 'Nightclub located on Avenida de la Bajamar, by the sea next to Playa de la Puntilla. Festive atmosphere with a coastal terrace. Currently temporarily closed.',
      desc_fr: 'Club nocturne sur Avenida de la Bajamar, au bord de la mer près de Playa de la Puntilla. Ambiance festive avec terrasse côtière. Actuellement temporairement fermé.',
      desc_de: 'Nachtclub an der Avenida de la Bajamar, am Meer neben der Playa de la Puntilla. Festliche Atmosphäre mit Küstentetrasse. Aktuell vorübergehend geschlossen.',
      desc_it: 'Club notturno situato in Avenida de la Bajamar, in riva al mare vicino alla Playa de la Puntilla. Atmosfera festosa con terrazza costiera. Attualmente temporaneamente chiuso.',
      address: 'Av. de la Bajamar, El Puerto de Santa María',
      hours_es: 'Temporalmente cerrado · Consultar redes sociales',
      hours_en: 'Temporarily closed · Check social media for updates',
      hours_it: 'Temporaneamente chiuso · Consulta i social media per aggiornamenti',
      phone: '+34 662 33 70 28',
      rating: '4.5★ (31)',
      link: 'https://maps.app.goo.gl/GiSgZ18XSrp8zCn27',
      maps: 'https://maps.google.com/?q=Lio+Club+Puntilla+Playa+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'cristalera', cat: 'nightlife', emoji: '🎹',
      name: 'Bar La Cristalera',
      badge_es: 'Piano bar junto al Guadalete', badge_en: 'Piano bar by the Guadalete', badge_fr: 'Piano bar au bord du Guadalete', badge_de: 'Piano-Bar am Guadalete', badge_it: 'Piano bar vicino al Guadalete',
      desc_es: 'Bar musical y piano bar en pleno centro, junto al río Guadalete. Música variada con DJ, con copas y ambiente animado. Terraza con acceso para silla de ruedas. Abre desde las 15:30.',
      desc_en: 'Music bar and piano bar in the city centre, by the Guadalete river. Varied music with DJ, drinks and lively atmosphere. Terrace with wheelchair access. Opens from 3:30 PM.',
      desc_fr: 'Bar musical et piano bar en plein centre, au bord du Guadalete. Musique variée avec DJ, cocktails et ambiance animée. Terrasse accessible en fauteuil roulant. Ouverture dès 15h30.',
      desc_de: 'Musikbar und Piano-Bar im Stadtzentrum am Fluss Guadalete. Abwechslungsreiche Musik mit DJ, Getränke und lebhafte Atmosphäre. Terrasse rollstuhlzugänglich. Öffnung ab 15:30 Uhr.',
      desc_it: 'Music bar e piano bar in pieno centro, vicino al fiume Guadalete. Musica varia con DJ, drink e atmosfera vivace. Terrazza con accesso per sedie a rotelle. Apre dalle 15:30.',
      address: 'Pl. de las Galeras Reales s/n, El Puerto de Santa María',
      hours_es: 'Lun–Jue: 15:30–22:00 · Vie–Sáb: 15:30–04:00 · Dom: 15:30–22:00',
      hours_en: 'Mon–Thu: 3:30 PM–10 PM · Fri–Sat: 3:30 PM–4:00 AM · Sun: 3:30 PM–10 PM',
      hours_it: 'Lun–Gio: 15:30–22:00 · Ven–Sab: 15:30–04:00 · Dom: 15:30–22:00',
      phone: '+34 647 84 54 47',
      rating: '3.9★',
      link: 'https://m.facebook.com/lacristaleracopas',
      maps: 'https://maps.google.com/?q=Bar+La+Cristalera+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'banana', cat: 'nightlife', emoji: '🍌',
      name: 'Banana Club',
      badge_es: 'La discoteca del Puerto', badge_en: 'El Puerto nightlife landmark', badge_fr: 'La discothèque du Puerto', badge_de: 'Die Diskothek des Hafens', badge_it: 'La discoteca del Puerto',
      desc_es: 'La discoteca más popular de El Puerto de Santa María, referente de la vida nocturna desde hace 5 años. Abre jueves a partir de las 23:00. Reservas por WhatsApp: 697 85 00 50.',
      desc_en: 'The most popular club in El Puerto de Santa María, a nightlife landmark for 5 years. Opens Thursday onwards at 11 PM. Bookings via WhatsApp: 697 85 00 50.',
      desc_fr: "Le club le plus populaire d'El Puerto de Santa María, une référence de la vie nocturne depuis 5 ans. Ouverture le jeudi à partir de 23h. Réservations WhatsApp: 697 85 00 50.",
      desc_de: 'Der beliebteste Club in El Puerto de Santa María, seit 5 Jahren ein Wahrzeichen des Nachtlebens. Öffnet donnerstags ab 23:00 Uhr. Reservierungen per WhatsApp: 697 85 00 50.',
      desc_it: 'La discoteca più popolare di El Puerto de Santa María, un punto di riferimento della vita notturna da 5 anni. Aperto dal giovedì dalle 23:00.',
      address: 'C. Ribera del Marisco 13, El Puerto de Santa María',
      hours_es: 'Jue: 23:00–tarde · Vie–Sáb: 23:00–tarde · Dom: 00:00–06:00',
      hours_en: 'Thu: 11 PM–late · Fri–Sat: 11 PM–late · Sun: midnight–6 AM',
      phone: '697 85 00 50 (WhatsApp)',
      rating: '2.4★',
      link: 'https://bananaelpuerto.com',
      maps: 'https://maps.google.com/?q=Banana+Club+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'castillo', cat: 'culture', emoji: '🏰',
      name: 'Castillo de San Marcos',
      name_en: 'San Marcos Castle',
      name_fr: 'Château de San Marcos',
      name_it: 'Castello di San Marcos',
      badge_es: 'Patrimonio histórico', badge_en: 'Historic heritage', badge_fr: 'Patrimoine historique', badge_de: 'Historisches Erbe', badge_it: 'Patrimonio storico',
      desc_es: 'Fortaleza del siglo XII construida sobre las ruinas de una mezquita árabe. Vinculada a los viajes de Colón y al ducado de Medinaceli. Incluye degustaciones de vino de jerez. 14.428 visitantes al año.',
      desc_en: "12th-century fortress built on the ruins of an Arab mosque. Linked to Columbus's voyages and the Duchy of Medinaceli. Includes sherry wine tastings. 14,428 visitors per year.",
      desc_fr: "Forteresse du XIIe siècle construite sur les ruines d'une mosquée arabe. Liée aux voyages de Christophe Colomb. Dégustations de xérès incluses.",
      desc_de: "Festung aus dem 12. Jahrhundert, auf den Ruinen einer arabischen Moschee erbaut. Mit Kolumbus' Reisen verbunden. Sherry-Weinverkostungen inklusive.",
      desc_it: 'Fortezza del XII secolo costruita sulle rovine di una moschea araba. Legata ai viaggi di Colombo e al ducato di Medinaceli. Include degustazioni di vino sherry. 14.428 visitatori all\'anno.',
      address: 'Plaza del Castillo s/n, El Puerto de Santa María',
      hours_es: 'Mar–Dom: 10:00–14:00 y 17:00–19:30 · Lunes cerrado',
      hours_en: 'Tue–Sun: 10am–2pm & 5pm–7:30pm · Closed Monday',
      hours_it: 'Mar–Dom: 10:00–14:00 e 17:00–19:30 · Lunedì chiuso',
      phone: '+34 956 851 751',
      rating: '4.4★ (14.428 visitas/año)',
      link: 'https://maps.google.com/?q=Castillo+San+Marcos+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Castillo+San+Marcos+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'plazatoros', cat: 'culture', emoji: '🐂',
      name: 'Real Plaza de Toros',
      name_en: 'Royal Bullring',
      name_fr: 'Arènes Royales',
      name_it: 'Arena Reale',
      badge_es: 'Monumento de 1880', badge_en: 'Monument from 1880', badge_fr: 'Monument de 1880', badge_de: 'Denkmal von 1880', badge_it: 'Monumento del 1880',
      desc_es: 'Plaza de toros construida en 1880, con aforo para 15.000 espectadores. Icónico monumento arquitectónico de El Puerto de Santa María. Visitas guíadas disponibles. Temporalmente cerrada.',
      desc_en: 'Bullring built in 1880 with a capacity of 15,000 spectators. Iconic architectural monument of El Puerto de Santa María. Guided tours available. Currently temporarily closed.',
      desc_fr: 'Arène construite en 1880, d’une capacité de 15 000 spectateurs. Monument architectural iconique d’El Puerto de Santa María. Visites guidées disponibles. Temporairement fermée.',
      desc_de: 'Stierkampfarena aus dem Jahr 1880 mit 15.000 Plätzen. Ikonisches Architekturmonument von El Puerto de Santa María. Führungen verfügbar. Vorübergehend geschlossen.',
      desc_it: 'Plaza de toros costruita nel 1880, con capienza per 15.000 spettatori. Iconico monumento architettonico di El Puerto de Santa María. Visite guidate disponibili. Temporaneamente chiusa.',
      address: 'Pl. de Elías Ahuja s/n, El Puerto de Santa María',
      hours_es: 'Temporalmente cerrada · Consultar web para eventos',
      hours_en: 'Temporarily closed · Check website for events',
      hours_it: 'Temporaneamente chiusa · Consulta il sito web per eventi',
      phone: null,
      rating: '4.3★',
      link: 'https://www.elpuertodesantamaria.es/plaza-de-toros/',
      maps: 'https://maps.google.com/?q=Real+Plaza+de+Toros+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'alberti', cat: 'culture', emoji: '🎨',
      name: 'Museo Fundación Rafael Alberti',
      name_en: 'Rafael Alberti Museum',
      name_fr: 'Musée Rafael Alberti',
      name_it: 'Museo Rafael Alberti',
      badge_es: 'Premio Cervantes 1983', badge_en: '1983 Cervantes Prize', badge_fr: 'Prix Cervantes 1983', badge_de: 'Cervantes-Preis 1983', badge_it: 'Premio Cervantes 1983',
      desc_es: 'Museo dedicado a Rafael Alberti, poeta y dramaturgo de El Puerto, Premio Cervantes 1983. Exposiciones permanentes y temporales sobre su vida y obra. Audio guías en varios idiomas. Entrada: 4,50€. Lunes cerrado.',
      desc_en: 'Museum dedicated to Rafael Alberti, poet and playwright from El Puerto, winner of the 1983 Cervantes Prize. Permanent and temporary exhibitions on his life and work. Audio guides in several languages. Entry: €4.50. Closed Mondays.',
      desc_fr: 'Musée dédié à Rafael Alberti, poète et dramaturge d’El Puerto, lauréat du Prix Cervantes 1983. Expositions permanentes et temporaires. Audioguides en plusieurs langues. Entrée : 4,50€. Fermé le lundi.',
      desc_de: 'Museum für Rafael Alberti, Dichter und Dramatiker aus El Puerto, Cervantes-Preisträger 1983. Dauer- und Wechselausstellungen. Audioguides in mehreren Sprachen. Eintritt: 4,50€. Montags geschlossen.',
      desc_it: 'Museo dedicato a Rafael Alberti, poeta e drammaturgo di El Puerto, Premio Cervantes 1983. Mostre permanenti e temporanee sulla sua vita e opera. Audioguide in diverse lingue. Ingresso: 4,50€. Lunedì chiuso.',
      address: 'C. Santo Domingo 25, El Puerto de Santa María',
      hours_es: 'Mar–Vie: 10:00–14:00 · Sáb–Dom: 11:00–14:00 · Lunes cerrado',
      hours_en: 'Tue–Fri: 10am–2pm · Sat–Sun: 11am–2pm · Closed Monday',
      hours_it: 'Mar–Ven: 10:00–14:00 · Sab–Dom: 11:00–14:00 · Lunedì chiuso',
      phone: '+34 626 48 29 69',
      rating: '4.6★ (489 reseñas)',
      link: 'http://www.rafaelalberti.com/',
      maps: 'https://maps.google.com/?q=Museo+Fundacion+Rafael+Alberti+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'valdivieso', cat: 'culture', emoji: '🏛️',
      name: 'Palacio de Valdivieso',
      name_en: 'Valdivieso Palace',
      name_fr: 'Palais de Valdivieso',
      name_it: 'Palazzo de Valdivieso',
      badge_es: 'Barroco s. XVIII', badge_en: '18th-c. Baroque', badge_fr: 'Baroque XVIIIe s.', badge_de: 'Barock 18. Jh.', badge_it: 'Barocco s. XVIII',
      desc_es: 'Palacio barroco del siglo XVIII situado en el centro histórico de El Puerto de Santa María. Uno de los ejemplos más destacados de la arquitectura palaciega de la ciudad. Fachada monumental en la Calle de la Palma.',
      desc_en: '18th-century Baroque palace in the historic centre of El Puerto de Santa María. One of the finest examples of palatial architecture in the city. Monumental facade on Calle de la Palma.',
      desc_fr: 'Palais baroque du XVIIIe siècle dans le centre historique d’El Puerto de Santa María. L’un des plus beaux exemples d’architecture palatiale de la ville.',
      desc_de: 'Barock-Palast aus dem 18. Jahrhundert im historischen Zentrum von El Puerto de Santa María. Eines der eindrucksvollsten Beispiele für Palastarchitektur der Stadt.',
      desc_it: 'Palazzo barocco del XVIII secolo situato nel centro storico di El Puerto de Santa María. Uno dei più begli esempi di architettura palaziale della città. Facciata monumentale in Calle de la Palma.',
      address: 'C. de la Palma 4, El Puerto de Santa María',
      hours_es: 'Exterior visible desde la calle · Consultar acceso interior',
      hours_en: 'Exterior visible from street · Check interior access',
      hours_it: 'Esterno visibile dalla strada · Consulta per l\'accesso interno',
      phone: null,
      rating: '4.5★',
      link: 'https://maps.google.com/?q=Palacio+de+Valdivieso+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Palacio+de+Valdivieso+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'aranibar', cat: 'culture', emoji: '🏩',
      name: 'Palacio de Araníbar',
      name_en: 'Araníbar Palace',
      name_fr: 'Palais de Araníbar',
      name_it: 'Palazzo de Araníbar',
      badge_es: 'Oficina de Turismo · Gratis', badge_en: 'Tourist Office · Free', badge_fr: 'Office de tourisme · Gratuit', badge_de: 'Touristikbüro · Kostenlos', badge_it: 'Ufficio del Turismo · Gratis',
      desc_es: 'Palacio histórico en el corazón de El Puerto que alberga la Oficina de Turismo municipal. Entrada gratuita con patio interior de gran valor arquitectónico. Centro de interpretación de la ciudad.',
      desc_en: 'Historic palace in the heart of El Puerto housing the municipal Tourist Office. Free entry with a historically significant interior courtyard. City interpretation centre.',
      desc_fr: 'Palais historique au cœur d’El Puerto abritant l’Office de tourisme municipal. Entrée gratuite avec une cour intérieure de grande valeur architecturale.',
      desc_de: 'Historischer Palast im Herzen von El Puerto, in dem das städtische Tourismusamt untergebracht ist. Freier Eintritt mit einem architektonisch wertvollen Innenhof.',
      desc_it: 'Palazzo storico nel cuore di El Puerto che ospita l\'Ufficio del Turismo municipale. Ingresso gratuito con cortile interno di grande valore architettonico.',
      address: 'Pl. Alfonso X el Sabio 9, El Puerto de Santa María',
      hours_es: 'Lun–Vie: 10:00–14:00 y 17:00–19:00 · Sáb–Dom: 10:00–14:00',
      hours_en: 'Mon–Fri: 10am–2pm & 5–7pm · Sat–Sun: 10am–2pm',
      phone: '+34 956 48 37 15',
      rating: '4.3★ (75 reseñas)',
      link: 'http://www.elpuertodesantamaria.es/',
      maps: 'https://maps.google.com/?q=Palacio+de+Aranibar+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'iglesia', cat: 'culture', emoji: '⛪',
      name: 'Iglesia Mayor Prioral',
      name_en: 'Priory Church',
      name_fr: 'Église Prieurale',
      name_it: 'Chiesa Maggiore Priore',
      badge_es: 'Gótico-renacentista s. XV', badge_en: 'Gothic-Renaissance 15th c.', badge_fr: 'Gothique-Renaissance XVe s.', badge_de: 'Gotik-Renaissance 15. Jh.', badge_it: 'Gotico-rinascimentale s. XV',
      desc_es: 'Principal templo católico de El Puerto de Santa María. Iglesia gótico-renacentista del siglo XV en la Plaza de España. 2.087 reseñas en Google. Misas diarias y visitas libres.',
      desc_en: 'Main Catholic church of El Puerto de Santa María. 15th-century Gothic-Renaissance architecture on Plaza de España. 2,087 Google reviews. Daily Mass and free visits.',
      desc_fr: 'Principal temple catholique d’El Puerto de Santa María. Architecture gothique-renaissance du XVe siècle sur la Plaza de España. 2 087 avis Google. Messes quotidiennes et visites libres.',
      desc_de: 'Hauptkirche von El Puerto de Santa María. Gotisch-Renaissance-Architektur aus dem 15. Jahrhundert auf der Plaza de España. 2.087 Google-Bewertungen. Tägliche Messen und freier Besuch.',
      desc_it: 'Principale tempio cattolico di El Puerto de Santa María. Architettura gotico-rinascimentale del XV secolo in Plaza de España. Messe quotidiane e visite libere.',
      address: 'Pl. de España s/n, El Puerto de Santa María',
      hours_es: 'Lun–Sáb: 8:30–13:00 y 18:00–21:00 · Dom: 8:30–14:00 y 18:30–21:00',
      hours_en: 'Mon–Sat: 8:30am–1pm & 6–9pm · Sun: 8:30am–2pm & 6:30–9pm',
      hours_it: 'Lun–Sab: 8:30–13:00 e 18:00–21:00 · Dom: 8:30–14:00 e 18:30–21:00',
      phone: '+34 956 85 17 16',
      rating: '4.5★ (2.087 reseñas)',
      link: 'https://iglesiamayorprioralelpuerto.com',
      maps: 'https://maps.google.com/?q=Iglesia+Mayor+Prioral+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'osborne', cat: 'gastro', emoji: '🍷',
      name: 'Bodegas Osborne',
      badge_es: 'Bodega histórica', badge_en: 'Historic winery', badge_fr: 'Bodega historique', badge_de: 'Historisches Weingut', badge_it: 'Cantina storica',
      desc_es: 'Fundada en 1772, es la bodega más visitada de El Puerto con 33.603 visitas/año. Alberga la mayor colección de vinos VORS del marco de Jerez y el icónico Toro de Osborne. Visitas guiadas en español, inglés y alemán.',
      desc_en: 'Founded in 1772, the most visited winery in El Puerto with 33,603 visits/year. Home to the largest VORS sherry wine collection and the iconic Osborne Bull. Guided tours in Spanish, English and German.',
      desc_fr: "Fondée en 1772, c'est la bodega la plus visitée d'El Puerto. Abrite la plus grande collection de vins VORS de la région de Jerez et le célèbre Taureau Osborne.",
      desc_de: 'Gegründet 1772, das meistbesuchte Weingut in El Puerto. Beherbergt die größte VORS-Sherry-Weinsammlung und den ikonischen Osborne-Stier.',
      desc_it: 'Fondata nel 1772, è la cantina più visitata di El Puerto. Ospita la più grande collezione di vini VORS di Jerez e l\'iconico Toro di Osborne.',
      address: 'Calle Los Moros 7, El Puerto de Santa María',
      hours_es: 'Lun–Dom: 10:00–15:00 · Verano también 19:00–22:00',
      hours_en: 'Mon–Sun: 10am–3pm · Summer also 7pm–10pm',
      hours_it: 'Lun–Dom: 10:00–15:00 · In estate anche 19:00–22:00',
      phone: '+34 956 869 100',
      rating: '4.5★',
      link: 'https://www.osborne.es',
      maps: 'https://maps.google.com/?q=Bodegas+Osborne+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'aponiente', cat: 'gastro', emoji: '⭐',
      name: 'Aponiente',
      badge_es: '3 Estrellas Michelin', badge_en: '3 Michelin Stars', badge_fr: '3 Étoiles Michelin', badge_de: '3 Michelin-Sterne', badge_it: '3 Stelle Michelin',
      desc_es: 'Restaurante de alta cocina del mar del chef Ángel León, "el Chef del Mar". 3 Estrellas Michelin, ubicado en un antiguo molino de mareas del siglo XIX. Menús degustación con maridaje de vinos.',
      desc_en: 'Fine dining seafood restaurant by chef Ángel León, "the Chef of the Sea". 3 Michelin Stars, located in a 19th-century tidal mill. Tasting menus with wine pairing.',
      desc_fr: "Restaurant gastronomique de la mer du chef Ángel León, 'le Chef de la Mer'. 3 Étoiles Michelin, dans un ancien moulin à marées du XIXe siècle.",
      desc_de: 'Fine-Dining-Meeresrestaurant von Küchenchef Ángel León, "dem Koch des Meeres". 3 Michelin-Sterne, in einer historischen Tidenmühle aus dem 19. Jahrhundert.',
      desc_it: 'Ristorante di alta cucina di mare dello chef Ángel León, "lo Chef del Mare". 3 Stelle Michelin, in un antico mulino a marea del XIX secolo.',
      address: 'C. Francisco Cossi Ochoa s/n, El Puerto de Santa María',
      hours_es: 'Mié–Dom: servicio de noche · Lun y Mar: cerrado',
      hours_en: 'Wed–Sun: dinner service · Mon & Tue: closed',
      hours_it: 'Mer–Dom: servizio serale · Lun e Mar: chiuso',
      phone: '+34 606 225 859',
      rating: '4.7★',
      link: 'https://aponiente.com',
      maps: 'https://maps.google.com/?q=Aponiente+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'ribera', cat: 'gastro', emoji: '🦞',
      name: 'Ribera del Marisco',
      badge_es: 'Paseo gastronómico', badge_en: 'Gastro promenade', badge_fr: 'Promenade gastronomique', badge_de: 'Gastronomiemeile', badge_it: 'Passeggiata gastronomica',
      desc_es: 'El paseo del marisco de El Puerto. Concentración de bares y restaurantes especializados en mariscos y pescados frescos junto al río Guadalete. Muy animado por las noches, especialmente en verano.',
      desc_en: "El Puerto's seafood promenade. Concentration of bars and restaurants specialising in fresh seafood along the Guadalete River. Very lively at night, especially in summer.",
      desc_fr: "La promenade des fruits de mer d'El Puerto. Concentration de bars et restaurants spécialisés dans les fruits de mer frais le long du Guadalete.",
      desc_de: 'El Puertos Meeresfrüchtepromenade. Konzentration von Bars und Restaurants, die frische Meeresfrüchte am Guadalete-Fluss servieren.',
      desc_it: 'La passeggiata del pesce di El Puerto. Concentrazione di bar e ristoranti specializzati in pesce fresco lungo il fiume Guadalete. Molto vivace di sera.',
      address: 'Ribera del Marisco, El Puerto de Santa María',
      hours_es: 'Mediodía y noche · Muy animado de 21:00 en adelante',
      hours_en: 'Lunch & dinner · Buzzing from 9 PM onwards',
      hours_it: 'Pranzo e cena · Molto vivace dalle 21:00 in poi',
      phone: null,
      rating: '★★★★★',
      link: 'https://maps.google.com/?q=Ribera+del+Marisco+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Ribera+del+Marisco+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'venencia', cat: 'gastro', emoji: '🐟',
      name: 'Restaurante La Venencia',
      badge_es: 'Cocina andaluza', badge_en: 'Andalusian cuisine', badge_fr: 'Cuisine andalouse', badge_de: 'Andalusische Küche', badge_it: 'Cucina andalusa',
      desc_es: 'Restaurante frente al mar en la Avenida de la Bajamar. Cocina tradicional andaluza y mariscos frescos con vistas a la marína. Accesible en silla de ruedas. Muy cerca del Real Club Náutico.',
      desc_en: "Seafront restaurant on Avenida de la Bajamar. Traditional Andalusian cuisine and fresh seafood with marina views. Wheelchair accessible. Very close to the Real Club Náutico.",
      desc_fr: 'Restaurant en bord de mer sur l\'Avenida de la Bajamar. Cuisine andalouse traditionnelle et fruits de mer frais avec vue sur la marina.',
      desc_de: 'Restaurant am Meer an der Avenida de la Bajamar. Traditionelle andalusische Küche und frische Meeresfrüchte mit Blick auf den Hafen.',
      desc_it: 'Ristorante fronte mare in Avenida de la Bajamar. Cucina tradizionale andalusa e pesce fresco con vista sulla marina. Accessibile in sedia a rotelle.',
      address: 'Av. de la Bajamar 78-80, El Puerto de Santa María',
      hours_es: 'Lun: 9:00–16:30 y 20:30–23:30 · Resto de días similar',
      hours_en: 'Mon: 9am–4:30pm & 8:30–11:30pm · Similar other days',
      hours_it: 'Lun: 9:00–16:30 e 20:30–23:30 · Altri giorni orari simili',
       phone: '+34 956 05 66 78',
      rating: '4.0★',
      link: 'https://maps.google.com/?q=Restaurante+La+Venencia+Bajamar+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Restaurante+La+Venencia+Bajamar+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'barpepito', cat: 'gastro', emoji: '🥘',
      name: 'Bar Pepito',
      badge_es: 'Tapas económicas', badge_en: 'Affordable tapas', badge_fr: 'Tapas abordables', badge_de: 'Günstige Tapas', badge_it: 'Tapas economiche',
      desc_es: 'Bar de tapas muy popular en El Puerto. Especialidad en coquinas y solomillo al queso de oveja. Excelente relación calidad-precio. 1.258 reseñas en Google · 10–20€ por persona.',
      desc_en: "Very popular tapas bar in El Puerto. Specialty: coquinas clams and beef fillet with sheep's cheese. Excellent value for money. 1,258 Google reviews · €10–20 per person.",
      desc_fr: "Bar à tapas très populaire à El Puerto. Spécialités : coquinas et filet de boeuf au fromage de brebis. Excellent rapport qualité-prix. 1 258 avis Google.",
      desc_de: 'Sehr beliebte Tapas-Bar in El Puerto. Spezialitäten: Coquinas-Muscheln und Rinderfilet mit Schafskäse. Hervorragendes Preis-Leistungs-Verhältnis. 1.258 Google-Bewertungen.',
      desc_it: 'Tapas bar molto popolare a El Puerto. Specialità: telline e filetto di manzo al formaggio di pecora. Ottimo rapporto qualità-prezzo.',
      address: 'C. Crucero Baleares 7, El Puerto de Santa María',
      hours_es: 'Mar–Vie: 9:00–16:00 y 20:00–23:30 · Sáb–Dom: 12:00–16:00 y 20:00–23:30 · Miércoles cerrado',
      hours_en: 'Tue–Fri: 9am–4pm & 8–11:30pm · Sat–Sun: 12–4pm & 8–11:30pm · Closed Wednesday',
      hours_it: 'Mar–Ven: 9:00–16:00 e 20:00–23:30 · Sab–Dom: 12:00–16:00 e 20:00–23:30 · Mercoledì chiuso',
       phone: '+34 956 85 42 54',
      rating: '4.3★ (1.258 reseñas)',
      link: 'https://maps.google.com/?q=Bar+Pepito+Crucero+Baleares+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Bar+Pepito+Crucero+Baleares+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'torotapas', cat: 'gastro', emoji: '🐂',
      name: 'Toro Tapas (Osborne)',
      badge_es: 'Tapas en Bodega', badge_en: 'Tapas at the Winery', badge_fr: 'Tapas dans la Bodega', badge_de: 'Tapas in der Bodega', badge_it: 'Tapas in Cantina',
      desc_es: 'Restaurante de tapas ubicado dentro de Bodegas Osborne. Cocina española de calidad en el corazón de la bodega más icónica de El Puerto. 2.713 reseñas · 4,4★.',
      desc_en: "Tapas restaurant inside the iconic Bodegas Osborne complex. Quality Spanish cuisine at the heart of El Puerto's most famous winery. 2,713 reviews · 4.4★.",
      desc_fr: "Restaurant de tapas situé à l'intérieur des Bodegas Osborne. Cuisine espagnole de qualité au cœur du domaine viticole le plus icônique d'El Puerto.",
      desc_de: 'Tapas-Restaurant innerhalb der ikonischen Bodegas Osborne. Qualitätsvolles spanisches Essen im Herzen des berühmtesten Weinguts von El Puerto.',
      desc_it: 'Ristorante di tapas situato all\'interno di Bodegas Osborne. Cucina spagnola di qualità nel cuore della cantina più iconica di El Puerto.',
      address: 'C. Los Moros 7, El Puerto de Santa María',
      hours_es: 'Lun: 8:30–00:00 · Cocina: 13:00–22:30',
      hours_en: 'Mon: 8:30am–midnight · Kitchen: 1pm–10:30pm',
      hours_it: 'Lun: 8:30–00:00 · Cucina: 13:00–22:30',
      phone: '+34 603 59 93 00',
      rating: '4.4★ (2.713 reseñas)',
      link: 'https://www.osborne.es/es/restaurante-osborne-toro-tapas-el-puerto-de-santa-maria',
      maps: 'https://maps.google.com/?q=Toro+Tapas+Bodegas+Osborne+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'ditaly', cat: 'gastro', emoji: '🍕',
      name: 'DITALY',
      badge_es: 'Italiano · 4,8★', badge_en: 'Italian · 4.8★', badge_fr: 'Italien · 4,8★', badge_de: 'Italienisch · 4,8★', badge_it: 'Italiano · 4,8★',
      desc_es: 'Restaurante italiano con una de las mejores valoraciones de El Puerto (4,8★ en Google con 974 reseñas). Especialidad en pizzas artesanas, pasta fresca y tiramiś de pistacho. Perfecto para compartir.',
      desc_en: "Italian restaurant with one of the best ratings in El Puerto (4.8★ on Google, 974 reviews). Specialises in artisan pizzas, fresh pasta and pistachio tiramisù. Perfect for sharing.",
      desc_fr: "Restaurant italien avec l'une des meilleures notes d'El Puerto (4,8★ sur Google, 974 avis). Spécialités : pizzas artisanales, pâtes fraîches et tiramisuù à la pistache.",
      desc_de: 'Italienisches Restaurant mit einer der besten Bewertungen in El Puerto (4,8★ bei Google, 974 Bewertungen). Spezialitäten: handgemachte Pizzas, frische Pasta und Pistazien-Tiramisù.',
      desc_it: 'Ristorante italiano con una delle migliori valutazioni di El Puerto. Specialità in pizze artigianali, pasta fresca e tiramisù al pistacchio.',
      address: 'C. Luna 1, El Puerto de Santa María',
      hours_es: 'Lun: abre a las 13:00 · Pico: 13:00–15:00 y 19:00–22:00',
      hours_en: 'Mon: opens at 1pm · Busy: 1–3pm lunch & 7–10pm dinner',
      hours_it: 'Lun: apre alle 13:00 · Picco: 13:00–15:00 e 19:00–22:00',
      phone: '+34 856 50 52 24',
      rating: '4.8★ (974 reseñas)',
      link: 'https://www.ditaly.es/locales/local-puerto-de-santa-maria/',
      maps: 'https://maps.google.com/?q=DITALY+Calle+Luna+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'tabernachef', cat: 'gastro', emoji: '🎣',
      name: 'La Taberna del Chef del Mar',
      badge_es: 'Universo Ángel León', badge_en: 'Ángel León Universe', badge_fr: 'Univers Ángel León', badge_de: 'Ángel León Universum', badge_it: 'Universo Ángel León',
      desc_es: 'Taberna vinculada al universo culinario del chef Ángel León (Aponiente, 3 estrellas Michelin). Tapas y platos de mariscos elevados en un ambiente informal y animado. 4,4★ en Google.',
      desc_en: "Tavern linked to the culinary universe of chef Ángel León (Aponiente, 3 Michelin stars). Elevated tapas and seafood dishes in a lively, informal atmosphere. 4.4★ on Google.",
      desc_fr: "Taverne liée à l'univers culinaire du chef Ángel León (Aponiente, 3 étoiles Michelin). Tapas et plats de fruits de mer élaborés dans une atmosphère informelle et animée.",
      desc_de: "Taverne, die mit der kulinarischen Welt von Köchefchef Ángel León (Aponiente, 3 Michelin-Sterne) verbunden ist. Gehobene Tapas und Meeresfrüchte in lockerer Atmosphäre.",
      desc_it: 'Taverna legata all\'universo culinario dello chef Ángel León (Aponiente, 3 stelle Michelin). Tapas e piatti di mare in un ambiente informale.',
      address: 'C. Puerto Escondido 6, El Puerto de Santa María',
      hours_es: 'Mar–Dom: abre 13:00 · Lunes cerrado',
      hours_en: 'Tue–Sun: opens 1pm · Closed Monday',
      hours_it: 'Mar–Dom: apre alle 13:00 · Lunedì chiuso',
      phone: '+34 956 11 20 93',
      rating: '4.4★',
      link: 'http://latabernadelchefdelmar.com/',
      maps: 'https://maps.google.com/?q=La+Taberna+del+Chef+del+Mar+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'romerijo', cat: 'gastro', emoji: '🦐',
      name: 'Romerijo',
      badge_es: 'Marisquería icónica', badge_en: 'Iconic seafood', badge_fr: 'Fruits de mer iconiques', badge_de: 'Ikone der Meeresfrüchte', badge_it: 'Pescheria iconica',
      desc_es: 'Marisquería icónica de El Puerto con más de 13.100 reseñas en Google. Especialidad en tortillitas de camarones, gambas y erizos. Temporalmente cerrado desde enero 2026 por un incendio en la sede de la Ribera del Marisco.',
      desc_en: "Iconic seafood institution in El Puerto with 13,100+ Google reviews. Famous for shrimp tortillas, prawns and sea urchins. Temporarily closed since January 2026 due to a fire at the Ribera del Marisco location.",
      desc_fr: "Institution iconique des fruits de mer à El Puerto avec plus de 13 100 avis Google. Célèbre pour les tortillitas de camarones, les crevettes et les oursins. Fermé temporairement depuis janvier 2026 (incendie).",
      desc_de: 'Ikonisches Meeresfrüchte-Restaurant in El Puerto mit über 13.100 Google-Bewertungen. Bekannt für Shrimp-Tortillas, Garnelen und Seeigel. Seit Januar 2026 vorübergehend geschlossen (Brand).',
      desc_it: 'Pescheria iconica di El Puerto con oltre 13.100 recensioni su Google. Specialità in tortillitas de camarones e ricci di mare. Temporaneamente chiusa da gennaio 2026.',
      address: 'C. Ribera del Marisco 1, El Puerto de Santa María',
      hours_es: 'Temporalmente cerrado · Reabrirá tras obras de renovación',
      hours_en: 'Temporarily closed · Will reopen after renovation works',
      hours_it: 'Temporaneamente chiusa · Riaprirà dopo i lavori di ristrutturazione',
      phone: '+34 956 54 12 54',
      rating: '4.0★ (13.100 reseñas)',
      link: 'https://romerijo.com',
      maps: 'https://maps.google.com/?q=Romerijo+Ribera+del+Marisco+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'colosia', cat: 'gastro', emoji: '🍷',
      name: 'Bodegas Gutiérrez Colosía',
      badge_es: 'Bodega histórica', badge_en: 'Historic winery', badge_fr: 'Bodega historique', badge_de: 'Historisches Weingut', badge_it: 'Cantina storica',
      desc_es: 'Bodega histórica a orillas del río Guadalete. Ofrece excelentes vinos de Jerez, degustaciones y visitas guiadas muy auténticas.',
      desc_en: 'Historic winery on the banks of the Guadalete river. Offers excellent sherry wines, tastings and very authentic guided tours.',
      desc_fr: 'Bodega historique sur les rives du fleuve Guadalete. Propose d\'excellents vins de Xérès, des dégustations et des visites guidées.',
      desc_de: 'Historisches Weingut am Ufer des Flusses Guadalete. Bietet hervorragende Sherry-Weine, Verkostungen und authentische Führungen.',
      desc_it: 'Cantina storica sulle rive del fiume Guadalete. Offre ottimi vini sherry, degustazioni e visite guidate molto autentiche.',
      address: 'Av. de la Bajamar 40, El Puerto de Santa María',
      hours_es: 'Lun-Sáb: 10:00–14:30',
      hours_en: 'Mon-Sat: 10am–2:30pm',
      hours_it: 'Lun-Sab: 10:00–14:30',
      phone: null,
      rating: '4.6★',
      link: 'https://maps.app.goo.gl/bbaPpTEj6affw9dA6',
      maps: 'https://maps.app.goo.gl/bbaPpTEj6affw9dA6',
    },
    {
      id: 'nuevadorada', cat: 'gastro', emoji: '🐟',
      name: 'La Nueva Dorada',
      badge_es: 'Mariscos frescos', badge_en: 'Fresh seafood', badge_fr: 'Fruits de mer', badge_de: 'Frische Meeresfrüchte', badge_it: 'Pesce fresco',
      desc_es: 'Clásico restaurante de mariscos y pescado frito situado en la famosa Ribera del Marisco. Ideal para comer pescaíto frito y raciones típicas.',
      desc_en: 'Classic seafood and fried fish restaurant located on the famous Ribera del Marisco. Ideal for fried fish and typical sharing plates.',
      desc_fr: 'Restaurant classique de fruits de mer et de poisson frit situé sur la célèbre Ribera del Marisco.',
      desc_de: 'Klassisches Fischrestaurant an der berühmten Ribera del Marisco. Ideal für gebratenen Fisch und typische Portionen.',
      desc_it: 'Classico ristorante di pesce fritto situato nella famosa Ribera del Marisco. Ideale per mangiare pesce fritto e porzioni tipiche.',
      address: 'C. Ribera del Marisco, El Puerto de Santa María',
      hours_es: 'Consultar horarios en Google',
      hours_en: 'Check Google for hours',
      hours_it: 'Controlla gli orari su Google',
      phone: null,
      rating: '4.2★',
      link: 'https://maps.app.goo.gl/n1Pwn5XpyEVKUkvK9',
      maps: 'https://maps.app.goo.gl/n1Pwn5XpyEVKUkvK9',
    },
    {
      id: 'newgoldbar', cat: 'gastro', emoji: '🍻',
      name: 'New Gold Bar',
      badge_es: 'Bar de tapas', badge_en: 'Tapas bar', badge_fr: 'Bar à tapas', badge_de: 'Tapas-Bar', badge_it: 'Bar di tapas',
      desc_es: 'Bar muy animado en el centro, ideal para tomar unas cervezas, copas y tapas con muy buen ambiente local.',
      desc_en: 'Very lively bar in the centre, ideal for beers, drinks and tapas with a great local atmosphere.',
      desc_fr: 'Bar très animé dans le centre, idéal pour boire des bières et des tapas avec une excellente ambiance locale.',
      desc_de: 'Sehr lebhafte Bar im Zentrum, ideal für Bier, Drinks und Tapas in toller lokaler Atmosphäre.',
      desc_it: 'Bar molto vivace in centro, ideale per bere una birra, un drink e tapas con un\'ottima atmosfera locale.',
      address: 'El Puerto de Santa María',
      hours_es: 'Consultar horarios en Google',
      hours_en: 'Check Google for hours',
      hours_it: 'Controlla gli orari su Google',
      phone: null,
      rating: '4.4★',
      link: 'https://maps.app.goo.gl/WufQrwsD8HyMm4uq7',
      maps: 'https://maps.app.goo.gl/WufQrwsD8HyMm4uq7',
    },
    {
      id: 'catamaran', cat: 'transport', emoji: '⛵',
      name: 'Catamarán → Cádiz',
      name_en: 'Catamaran → Cádiz',
      name_fr: 'Catamaran → Cadix',
      name_de: 'Katamaran → Cádiz',
      name_it: 'Catamarano → Cadice',
      badge_es: 'Transporte marítimo', badge_en: 'Sea transport', badge_fr: 'Transport maritime', badge_de: 'Seetransport', badge_it: 'Trasporto marittimo',
      desc_es: 'La forma más bonita de visitar Cádiz. El catamarán sale desde la Estación Marítima de El Puerto con más de 15 travesías al día. Solo 25–30 minutos de trayecto con vistas a la bahía.',
      desc_en: "The most beautiful way to visit Cádiz. The catamaran departs from El Puerto's Maritime Station with 15+ crossings daily. Just 25–30 minutes crossing with bay views.",
      desc_fr: "La plus belle façon de visitar Cádiz. Le catamaran part de la gare maritime d'El Puerto avec plus de 15 traversées par jour. Seulement 25–30 minutes de trajet.",
      desc_de: 'Der schönste Weg nach Cádiz. Das Katamaran fährt vom Seebahnhof El Puerto mit 15+ täglichen Überfahrten. Nur 25–30 Minuten Fahrtzeit mit Blick auf die Bucht.',
      desc_it: 'Il modo più bello per visitare Cadice. Il catamarano parte dalla Stazione Marittima con oltre 15 partenze al giorno.',
      address: 'Estación Marítima, El Puerto de Santa María',
      hours_es: '15+ travesías/día · Primera salida ~07:00 · Última ~22:00',
      hours_en: '15+ crossings/day · First departure ~7am · Last ~10pm',
      hours_it: '15+ corse/giorno · Prima partenza ~07:00 · Ultima ~22:00',
      phone: null,
      rating: null,
      link: 'https://maps.google.com/?q=Estacion+Maritima+El+Puerto+de+Santa+Maria',
      maps: 'https://maps.google.com/?q=Estacion+Maritima+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'tren', cat: 'transport', emoji: '🚆',
      name: 'Estación de Tren',
      name_en: 'Train Station',
      name_fr: 'Gare Ferroviaire',
      name_de: 'Bahnhof',
      name_it: 'Stazione Ferroviaria',
      badge_es: 'Renfe Cercanías C1', badge_en: 'Renfe Cercanías C1', badge_fr: 'Renfe Cercanías C1', badge_de: 'Renfe Cercanías C1', badge_it: 'Renfe Cercanías C1',
      desc_es: 'Estación de tren gestionada por Adif. Cercanías C1 con conexiones a Cádiz (~30 min), Jerez de la Frontera (~15 min) y Sevilla (~1h). También sirven Alvia (alta velocidad) y trenes de Media Distancia. Totalmente accesible.',
      desc_en: 'Train station managed by Adif. Cercanías C1 with connections to Cádiz (~30 min), Jerez de la Frontera (~15 min) and Seville (~1h). Also served by Alvia (high-speed) and Media Distancia regional trains. Fully accessible.',
      desc_fr: 'Gare ferroviaire gérée par Adif. Cercanías C1 avec liaisons vers Cádiz (~30 min), Jerez de la Frontera (~15 min) et Séville (~1h). Également desservie par Alvia (grande vitesse) et trains régionaux. Entièrement accessible.',
      desc_de: 'Bahnhof, verwaltet von Adif. Cercanías C1 mit Verbindungen nach Cádiz (~30 Min.), Jerez de la Frontera (~15 Min.) und Sevilla (~1 Std.). Auch Alvia (Hochgeschwindigkeit) und Regionalzüge. Vollständig barrierefrei.',
      desc_it: 'Stazione ferroviaria gestita da Adif. Cercanías C1 per Cadice (~30 min), Jerez (~15 min) e Siviglia (~1h).',
      address: 'Pl. de la Estación s/n, El Puerto de Santa María',
      hours_es: 'Horario según trenes Renfe · Consultar renfe.com',
      hours_en: 'Schedule per Renfe timetable · Check renfe.com',
      hours_it: 'Orario secondo i treni Renfe · Consulta renfe.com',
      phone: '+34 902 43 23 43',
      rating: '3.0★',
      link: 'https://www.renfe.com/es/es/cercanias/cercanias-cadiz',
      maps: 'https://maps.google.com/?q=Estacion+Tren+Puerto+de+Santa+Maria',
    },
    {
      id: 'torunos', cat: 'nature', emoji: '🌿',
      name: 'Parque Natural Los Toruños',
      name_en: 'Los Toruños Natural Park',
      name_fr: 'Parc Naturel Los Toruños',
      name_it: 'Parco Naturale Los Toruños',
      badge_es: 'Reserva natural de marismas', badge_en: 'Tidal marsh nature reserve', badge_fr: 'Réserve naturelle de marécage', badge_de: 'Naturschutzgebiet Wattenmeer', badge_it: 'Riserva naturale paludi',
      desc_es: 'Reserva natural de marismas con paseos de madera, alquiler de kayaks y bicicletas, observación de aves y zonas de picnic. Acceso libre 24 horas. Tel: +34 856 58 05 24.',
      desc_en: 'Tidal marsh nature reserve with boardwalks, kayak & bike rental, birdwatching and picnic areas. Free access, open 24 hours. Tel: +34 856 58 05 24.',
      desc_fr: "Réserve naturelle de marécage avec passerelles en bois, location de kayaks et vélos, observation des oiseaux. Accès libre 24h/24.",
      desc_de: 'Naturschutzgebiet mit Holzstegen, Kajak- und Fahrradverleih, Vogelbeobachtung und Picknickplätzen. Freier Zugang rund um die Uhr.',
      desc_it: 'Riserva naturale con passerelle in legno, noleggio kayak e biciclette, birdwatching e aree picnic. Accesso libero 24 ore su 24.',
      address: 'Av. del Mar 7, El Puerto de Santa María',
      hours_es: 'Abierto 24 horas · Acceso libre',
      hours_en: 'Open 24 hours · Free access',
      hours_it: 'Aperto 24 ore · Accesso libero',
      phone: '+34 856 58 05 24',
      rating: '4.7★',
      link: 'https://www.juntadeandalucia.es/medioambiente/portal/areas-tematicas/espacios-naturales-protegidos',
      maps: 'https://maps.google.com/?q=36.572096,-6.2162876',
    },
    {
      id: 'rcn', cat: 'nautica', emoji: '⚓',
      name: 'Real Club Náutico',
      badge_es: 'Náutica · Gastronomía · Deporte', badge_en: 'Nautical · Gastronomy · Sport', badge_fr: 'Nautique · Gastronomie · Sport', badge_de: 'Nautik · Gastronomie · Sport', badge_it: 'Nautica · Gastronomia · Sport',
      desc_es: 'Club náutico histórico a orillas del Guadalete. Restaurante-bar La Venecia (tapas y arroces), club de copas Chang Bay, pantalán con alquiler de motos de agua y embarcaciones con o sin patrón. Pistas de pádel y tenis.',
      desc_en: 'Historic yacht club on the Guadalete. La Venecia restaurant-bar (tapas & rice), Chang Bay club, pontoon with jet ski & boat rental (skippered or bareboat). Padel and tennis courts.',
      desc_fr: "Club nautique historique au bord du Guadalete. Restaurant La Venecia (tapas et riz), club Chang Bay, ponton avec location de jet skis et bateaux. Courts de padel et tennis.",
      desc_de: 'Historischer Yachtclub am Guadalete. Restaurant La Venecia (Tapas & Reis), Club Chang Bay, Steg mit Jetski- und Bootsverleih. Padel- und Tennisplätze.',
      desc_it: 'Storico yacht club sulle rive del fiume Guadalete. Ristorante La Venecia, club Chang Bay, noleggio moto d\'acqua. Campi da paddle e tennis.',
      address: 'Avenida de la Bajamar 13, El Puerto de Santa María',
      hours_es: 'La Venecia: 09:00–00:00 · Chang Bay: 15:00–02:00',
      hours_en: 'La Venecia: 9am–midnight · Chang Bay: 3pm–2am',
      hours_it: 'La Venecia: 09:00–00:00 · Chang Bay: 15:00–02:00',
      phone: null,
      rating: '★★★★',
      link: 'https://www.rcnpsm.es',
      maps: 'https://maps.google.com/?q=Real+Club+Nautico+El+Puerto+de+Santa+Maria',
    },
    {
      id: 'mercadona', cat: 'supermercado', emoji: '🛒',
      name: 'Supermercados El Jamón',
      badge_es: 'Supermercado · 6 min a pie', badge_en: 'Supermarket · 6 min walk',
      badge_fr: 'Supermarché · 6 min à pied', badge_de: 'Supermarkt · 6 Min. zu Fuß', badge_it: 'Supermercato · 6 min a piedi',
      desc_es: 'El supermercado más cercano al Airbnb, a solo 6 minutos caminando. Supermercados El Jamón es una querida cadena andaluza con amplia selección de frutas y verduras frescas, carnes, embutidos ibéricos, panadería y productos de proximidad a precios competitivos.',
      desc_en: 'The closest supermarket to the Airbnb, just a 6-minute walk away. El Jamón is a beloved Andalusian chain with a wide selection of fresh fruit and vegetables, meats, Iberian cold cuts, bakery and local products at competitive prices.',
      desc_fr: 'Le supermarché le plus proche de l\'Airbnb, à seulement 6 minutes à pied. Supermercados El Jamón est une chaîne andalouse appréciée proposant fruits et légumes frais, viandes, charcuterie ibérique, boulangerie et produits locaux à prix compétitifs.',
      desc_de: 'Der nächstgelegene Supermarkt zum Airbnb, nur 6 Gehminuten entfernt. Supermercados El Jamón ist eine beliebte andalusische Kette mit frischem Obst und Gemüse, Fleisch, iberischer Wurst, Bäckerei und regionalen Produkten zu günstigen Preisen.',
      desc_it: 'Il supermercato più vicino all\'Airbnb, a soli 6 minuti a piedi. El Jamón è una catena andalusa con una vasta selezione di prodotti freschi e locali.',
      address: 'Av. de la Bajamar, El Puerto de Santa María',
      hours_es: 'Lun–Sáb: 09:00–21:30 · Dom: 09:00–15:00',
      hours_en: 'Mon–Sat: 9:00 AM–9:30 PM · Sun: 9:00 AM–3:00 PM',
      hours_fr: 'Lun–Sam: 09h00–21h30 · Dim: 09h00–15h00',
      hours_de: 'Mo–Sa: 09:00–21:30 Uhr · So: 09:00–15:00 Uhr',
      hours_it: 'Lun–Sab: 09:00–21:30 · Dom: 09:00–15:00',
      phone: null, rating: '4.1★',
    },
    {
      id: 'aldi', cat: 'supermercado', emoji: '🛒',
      name: 'Aldi',
      badge_es: 'Supermercado · Precios bajos', badge_en: 'Supermarket · Low prices',
      badge_fr: 'Supermarché · Prix bas', badge_de: 'Supermarkt · Niedrigpreise', badge_it: 'Supermercato · Prezzi bassi',
      desc_es: 'Supermercado Aldi en El Puerto de Santa María. Precios bajos garantizados, excelente sección de productos frescos, artículos de temporada y marcas propias de calidad. 4,2★ con 1.379 reseñas.',
      desc_en: 'Aldi supermarket in El Puerto de Santa María. Guaranteed low prices, excellent fresh produce section, seasonal items and quality own-brand products. 4.2★ with 1,379 reviews.',
      desc_fr: 'Supermarché Aldi à El Puerto de Santa María. Prix bas garantis, excellente section de produits frais, articles de saison et marques propres de qualité.',
      desc_de: 'Aldi-Supermarkt in El Puerto de Santa María. Garantiert niedrige Preise, hervorragende Frischwarenabteilung, Saisonartikel und Eigenmarken in hoher Qualität.',
      desc_it: 'Supermercato Aldi a El Puerto de Santa María. Prezzi bassi garantiti, ottima sezione di prodotti freschi e articoli stagionali.',
      address: 'C. Valdés s/n, El Puerto de Santa María',
      hours_es: 'Lun–Sáb: 09:00–21:30 · Domingo cerrado',
      hours_en: 'Mon–Sat: 9:00 AM–9:30 PM · Sunday closed',
      hours_it: 'Lun–Sab: 09:00–21:30 · Domenica chiusa',
      phone: null, rating: '4.2★ (1.379 reseñas)',
      link: 'https://maps.app.goo.gl/eLoWrx2oRU8eyNKa9',
      maps: 'https://maps.app.goo.gl/eLoWrx2oRU8eyNKa9',
    },
    {
      id: 'mercadona2', cat: 'supermercado', emoji: '🛒',
      name: 'Mercadona Dunas',
      badge_es: 'Supermercado · Zona Dunas', badge_en: 'Supermarket · Dunas area',
      badge_fr: 'Supermarché · Zone Dunas', badge_de: 'Supermarkt · Dunas-Zone', badge_it: 'Supermercato · Zona Dunas',
      desc_es: 'Segundo Mercadona de El Puerto, en la zona de Ronda de las Dunas. Gran superficie con amplio parking gratuito, sección de frescos completa, panadería y productos locales andaluces. 4,1★ con 2.107 reseñas.',
      desc_en: 'Second Mercadona in El Puerto, in the Ronda de las Dunas area. Large store with free parking, full fresh produce section, bakery and local Andalusian products. 4.1★ with 2,107 reviews.',
      desc_fr: 'Deuxième Mercadona d\'El Puerto, dans la zone Ronda de las Dunas. Grand magasin avec parking gratuito, section fraîche complète et prodotti locali andalusi.',
      desc_de: 'Zweiter Mercadona in El Puerto, im Bereich Ronda de las Dunas. Großes Geschäft mit kostenlosem Parkplatz und vollständiger Frischwarenabteilung.',
      desc_it: 'Secondo Mercadona di El Puerto, in zona Ronda de las Dunas. Grande supermercato con parcheggio gratuito.',
      address: 'Rda. de las Dunas 7, El Puerto de Santa María',
      hours_es: 'Lun–Sáb: 09:00–21:30 · Domingo cerrado',
      hours_en: 'Mon–Sat: 9:00 AM–9:30 PM · Sunday closed',
      hours_it: 'Lun–Sab: 09:00–21:30 · Domenica chiusa',
      phone: null, rating: '4.1★ (2.107 reseñas)',
      link: 'https://maps.app.goo.gl/iMzrKyCVCL2jZtUU6',
      maps: 'https://maps.app.goo.gl/iMzrKyCVCL2jZtUU6',
    },
    {
      id: 'dia', cat: 'supermercado', emoji: '🛒',
      name: 'Supermercados Dia',
      badge_es: 'Supermercado · Oferta diaria', badge_en: 'Supermarket · Daily deals',
      badge_fr: 'Supermarché · Offres quotidiennes', badge_de: 'Supermarkt · Tagesangebote', badge_it: 'Supermercato · Offerte del giorno',
      desc_es: 'Supermercados Dia, cadena española con excelente relación calidad-precio. Amplia variedad de productos de marca propia y ofertas diarias. Muy conveniente para las compras del día a día.',
      desc_en: 'Dia supermarket chain from Spain with great value for money. Wide range of own-brand products and daily deals. Very convenient for everyday shopping.',
      desc_fr: 'Chaîne espagnole Dia avec un excellent rapport qualità-prix. Large gamme de prodotti de marque propre et offerte quotidiane. Très pratique pour les achats du quotidien.',
      desc_de: 'Spanische Supermarktkette Dia mit hervorragendem Preis-Leistungs-Verhältnis. Breites Sortiment an Eigenmarken und täglichen Angeboten.',
      desc_it: 'Catena spagnola Dia con ottimo rapporto qualità-prezzo. Ampia gamma di prodotti di marca propria e offerte giornaliere.',
      address: 'Av. Pintor Antonio Fernández Sevilla 18A, El Puerto de Santa María',
      hours_es: 'Lun–Sáb: 09:00–21:30 · Domingo cerrado',
      hours_en: 'Mon–Sat: 9:00 AM–9:30 PM · Sunday closed',
      hours_it: 'Lun–Sab: 09:00–21:30 · Domenica chiusa',
      phone: null, rating: '3.9★ (282 reseñas)',
      link: 'https://maps.app.goo.gl/ZtKo7JEHFALN6Zho9',
      maps: 'https://maps.app.goo.gl/ZtKo7JEHFALN6Zho9',
    },
    {
      id: 'puertosherry', cat: 'nautica', emoji: '⚓',
      name: 'Puerto Sherry Marina',
      badge_es: 'Marina deportiva', badge_en: 'Sports marina', badge_fr: 'Marina sportive', badge_de: 'Sporthafen', badge_it: 'Marina sportiva',
      desc_es: 'Marina moderna con più di 700 ormeggi, club nautici, scuole di vela e ristoranti con vista sulla baia di Cadice. Tramonti spettacolari.',
      desc_en: 'Modern marina with over 700 berths, yacht clubs, sailing school and restaurants overlooking the Bay of Cádiz. Spectacular sunsets over the Atlantic.',
      desc_fr: "Marina moderne avec plus de 700 places, clubs nautiques, école de voile et restaurants avec vue sur la baie de Cádiz.",
      desc_de: 'Moderne Marina mit über 700 Liegeplätzen, Yachtclubs, Segelschule und Restaurants mit Blick auf die Bucht von Cádiz.',
      desc_it: 'Marina moderna con oltre 700 posti barca, yacht club, scuola di vela e ristoranti. Tramonti spettacolari.',
      address: 'Puerto Sherry, El Puerto de Santa María',
      hours_es: 'Abierto todos los días',
      hours_en: 'Open every day',
      hours_it: 'Aperto ogni giorno',
      phone: '+34 956 870 103',
      rating: '★★★★★',
      link: 'https://maps.google.com/?q=Puerto+Sherry+Marina',
      maps: 'https://maps.google.com/?q=Puerto+Sherry+Marina',
    },
  ];
